/**
* OpenPerf API
* REST API interface for OpenPerf
*
* OpenAPI spec version: 1
* Contact: support@spirent.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#include "PacketGeneratorResult_clock_sync.h"

namespace swagger {
namespace v1 {
namespace model {

PacketGeneratorResult_clock_sync::PacketGeneratorResult_clock_sync()
{
    m_Units = "";
    
}

PacketGeneratorResult_clock_sync::~PacketGeneratorResult_clock_sync()
{
}

void PacketGeneratorResult_clock_sync::validate()
{
    // TODO: implement validation
}

nlohmann::json PacketGeneratorResult_clock_sync::toJson() const
{
    nlohmann::json val = nlohmann::json::object();

    val["summary"] = ModelBase::toJson(m_Summary);
    val["units"] = ModelBase::toJson(m_Units);
    

    return val;
}

void PacketGeneratorResult_clock_sync::fromJson(nlohmann::json& val)
{
    setUnits(val.at("units"));
    
}


std::shared_ptr<PacketGeneratorResult_clock_sync_summary> PacketGeneratorResult_clock_sync::getSummary() const
{
    return m_Summary;
}
void PacketGeneratorResult_clock_sync::setSummary(std::shared_ptr<PacketGeneratorResult_clock_sync_summary> value)
{
    m_Summary = value;
    
}
std::string PacketGeneratorResult_clock_sync::getUnits() const
{
    return m_Units;
}
void PacketGeneratorResult_clock_sync::setUnits(std::string value)
{
    m_Units = value;
    
}

}
}
}

