/**
* OpenPerf API
* REST API interface for OpenPerf
*
* OpenAPI spec version: 1
* Contact: support@spirent.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#include "PacketAnalyzerResult_clock_sync.h"

namespace swagger {
namespace v1 {
namespace model {

PacketAnalyzerResult_clock_sync::PacketAnalyzerResult_clock_sync()
{
    m_Units = "";
    
}

PacketAnalyzerResult_clock_sync::~PacketAnalyzerResult_clock_sync()
{
}

void PacketAnalyzerResult_clock_sync::validate()
{
    // TODO: implement validation
}

nlohmann::json PacketAnalyzerResult_clock_sync::toJson() const
{
    nlohmann::json val = nlohmann::json::object();

    val["summary"] = ModelBase::toJson(m_Summary);
    val["units"] = ModelBase::toJson(m_Units);
    

    return val;
}

void PacketAnalyzerResult_clock_sync::fromJson(nlohmann::json& val)
{
    setUnits(val.at("units"));
    
}


std::shared_ptr<PacketAnalyzerFlowSummaryCounters> PacketAnalyzerResult_clock_sync::getSummary() const
{
    return m_Summary;
}
void PacketAnalyzerResult_clock_sync::setSummary(std::shared_ptr<PacketAnalyzerFlowSummaryCounters> value)
{
    m_Summary = value;
    
}
std::string PacketAnalyzerResult_clock_sync::getUnits() const
{
    return m_Units;
}
void PacketAnalyzerResult_clock_sync::setUnits(std::string value)
{
    m_Units = value;
    
}

}
}
}

