/**
* OpenPerf API
* REST API interface for OpenPerf
*
* OpenAPI spec version: 1
* Contact: support@spirent.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
/*
 * PacketAnalyzerResult_clock_sync.h
 *
 * Clock sync statistics for analyzer
 */

#ifndef PacketAnalyzerResult_clock_sync_H_
#define PacketAnalyzerResult_clock_sync_H_


#include "ModelBase.h"

#include "PacketAnalyzerFlowSummaryCounters.h"
#include <string>

namespace swagger {
namespace v1 {
namespace model {

/// <summary>
/// Clock sync statistics for analyzer
/// </summary>
class  PacketAnalyzerResult_clock_sync
    : public ModelBase
{
public:
    PacketAnalyzerResult_clock_sync();
    virtual ~PacketAnalyzerResult_clock_sync();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    nlohmann::json toJson() const override;
    void fromJson(nlohmann::json& json) override;

    /////////////////////////////////////////////
    /// PacketAnalyzerResult_clock_sync members

    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<PacketAnalyzerFlowSummaryCounters> getSummary() const;
    void setSummary(std::shared_ptr<PacketAnalyzerFlowSummaryCounters> value);
        /// <summary>
    /// Clock sync error measurement units
    /// </summary>
    std::string getUnits() const;
    void setUnits(std::string value);
    
protected:
    std::shared_ptr<PacketAnalyzerFlowSummaryCounters> m_Summary;

    std::string m_Units;

};

}
}
}

#endif /* PacketAnalyzerResult_clock_sync_H_ */
