/**
* OpenPerf API
* REST API interface for OpenPerf
*
* OpenAPI spec version: 1
* Contact: support@spirent.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
/*
 * PacketGeneratorResult_clock_sync.h
 *
 * Clock sync statistics for generator
 */

#ifndef PacketGeneratorResult_clock_sync_H_
#define PacketGeneratorResult_clock_sync_H_


#include "ModelBase.h"

#include <string>
#include "PacketGeneratorResult_clock_sync_summary.h"

namespace swagger {
namespace v1 {
namespace model {

/// <summary>
/// Clock sync statistics for generator
/// </summary>
class  PacketGeneratorResult_clock_sync
    : public ModelBase
{
public:
    PacketGeneratorResult_clock_sync();
    virtual ~PacketGeneratorResult_clock_sync();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    nlohmann::json toJson() const override;
    void fromJson(nlohmann::json& json) override;

    /////////////////////////////////////////////
    /// PacketGeneratorResult_clock_sync members

    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<PacketGeneratorResult_clock_sync_summary> getSummary() const;
    void setSummary(std::shared_ptr<PacketGeneratorResult_clock_sync_summary> value);
        /// <summary>
    /// clock sync error measurement units
    /// </summary>
    std::string getUnits() const;
    void setUnits(std::string value);
    
protected:
    std::shared_ptr<PacketGeneratorResult_clock_sync_summary> m_Summary;

    std::string m_Units;

};

}
}
}

#endif /* PacketGeneratorResult_clock_sync_H_ */
