
version: 2
jobs:
  build:
    machine:
      enabled: true

    working_directory: /

    steps:
      - run:
          name: Docker Pull from hub
          command: docker pull spirentorion/inception-core:0.0.1

      - run:
          name: Running docker on machine executor
          command: docker run -it --privileged spirentorion/inception-core:0.0.1

      - checkout

      - run: cd inception-core

      - run:
          name: Run build and aat tests
          command: make all -j $(grep -c ^processor /proc/cpuinfo) && make test

      - store_artifacts:
          path: /inception-core/tests/aat/*.log
          destination: inception-log
