version: 2
jobs:
  build:
    machine:
      image: circleci/classic:latest

    steps:
      - checkout

      - run:
          name: Pull latest build container
          command: docker pull spirentorion/inception-core:latest

      - run:
          name: Run containerized build and test
          command: docker run -it --privileged -v ~/project:/project spirentorion/inception-core:latest /bin/bash -c "cd /project && make all -j $(grep -c ^processor /proc/cpuinfo) && make test"

      - store_artifacts:
          path: ~/project/tests/aat/*.log
          destination: inception-log
