
version: 2
jobs:
  build:
    machine:
      image: circleci/classic:latest

    steps:
      - checkout

      - run:
          name: Docker Pull latest from hub
          command: docker pull spirentorion/inception-core:latest

      - run:
          name: Running docker on machine executor. Run build and make tests
          command: docker run -it --privileged -v ~/project:/project -v /proc:/proc spirentorion/inception-core:latest /bin/bash -c "cd /project && make all -j $(grep -c ^processor /proc/cpuinfo) && make test“

      - store_artifacts:
          path: ~/project/tests/aat/*.log
          destination: inception-log
